apiVersion: v1
kind: Service
metadata:
  name: fuel-consumption-service
spec:
  selector:
    app: fuel-consumption-app
  ports:
    - protocol: TCP
      port: 80
      targetPort: 8080
  type: NodePort
  